### PR TITLE
Provide more puns for upstream

### PR DESCRIPTION
**Pull request by fritzmark**
If I should change something just ask.

### CODE REVIEW

**Comment by derphilipp** [comment]
Can you remove the non-joke text elements? Feel free to shoutout them in the PR, but not in the textfile;

**Comment by fritzmark** [comment]
Sure will do.

**Comment by derphilipp** [comment]
I would like to keep it as simple as possible;
there are already some duplicates when it comes to the punchline

**Comment by fritzmark** [comment]
Kay will be removed to.

**Pull request merged**
